### PR TITLE
Theme tokens type update

### PR DESCRIPTION
**Pull request by huijiewei**
add number

### CODE REVIEW

**Comment by mattcompiles** [comment]
Hi, thanks for the PR. 

However, only allowing `string` is an explicit decision due to the nature of CSS Variables. Almost all of the time your variables will need a unit (e.g. `em` or `px`) to work as expected when consumed in styles. 

If you feel like there's something we're missing here feel free to open up a discussion topic to discuss it 😄

**Comment by huijiewei** [comment]
Thanks, but fontWeight or lineHeight should set be number

**Comment by markdalgleish** [comment]
Unitless numbers can still be provided as strings, e.g. `myFontWeight: '400'`. The idea is that it's forcing you to be explicit that it's unitless.

**Comment by markdalgleish** [comment]
The reason we do this for variables and _don't_ do this for styles is that we have no idea where a variable will be used, so there's no way for us to infer whether it needs a unit applied or not.

**Comment by maraisr** [comment]
The grid properties do not work w/o the literal number eg:

grid-column-start: "1"; ❌
grid-column-start: 1; ✅

cc @markdalgleish @mattcompiles

**Comment by madou** [comment]
That's still `'1'` though.

If you wanted the quotes I'm sure you'd need to add them, like:

`"1"`

**Comment by maraisr** [comment]
have you tried this? `'1'` doesnt work: https://codepen.io/marais/pen/wvgOwdx 

cc @madou

**Comment by michaeltaranto** [comment]
To be clear, this discussion is about the input structure, which accepts css as an object with string values. The resulting values won't have any quotes.

For example, `{ gridColumnStart: '1' }` will be output as `grid-column-start: 1`. Same goes for  `{ display: 'block' }`, the quotes don't end up in the CSS.

**Comment by maraisr** [comment]
seems fair! Buncha legends you folk.

**Comment by huijiewei** [comment]
The point is I don't like it  ```fontWeight: (themeVars.fontWeights.medium as unknown) as number```

**Comment by mattcompiles** [comment]
@huijiewei I agree with you that this is an issue. All properties should support CSS Variables as input without casting.

**Comment by mattcompiles** [comment]
@huijiewei #50 Should resolve this issue 👍

**Pull request closed without merging**
